return {
-- 	"stevearc/conform.nvim",
-- 	opts = {},
-- 	config = function()
-- 		require("conform").setup({
-- 			formatters_by_ft = {
-- 				html = { "prettierd", "prettier", stop_after_first = true },
-- 				javascript = { "prettierd", "prettier", stop_after_first = true },
-- 				typescript = { "prettierd", "prettier", stop_after_first = true },
-- 				lua = { "stylua" },
-- 			},
-- 			format_on_save = {
-- 				timeout_ms = 500,
-- 				lsp_fallback = true,
-- 			},
-- 			formatters = {
-- 				prettierd = {
-- 					args = { "--tab-width 2" },
-- 				},
-- 			},
-- 		})
-- 	end,
}
